# Generated by Django 6.0 on 2026-01-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_product_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerModel',
        ),
    ]
